version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/todo-app-server
permissions:
  - object: /home/ubuntu/todo-app-server/scripts
    pattern: "**"
    owner: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/application_before_install.sh
      timeout: 50
      runas: root
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 50
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 200
      runas: ubuntu