version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/todo-app-server
hook:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 40
      runas: ubuntu
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 120
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 120
      runas: ec2-user

   