version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/todo-app-server
hook:
  ApplicationStop:
    - location: scripts/application/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/application/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application/application_start.sh
      timeout: 300
      runas: ec2-user

   