version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/todo-app-server
permissions:
  - object: /home/ubuntu/todo-app-server/scripts
    pattern: "**"
    owner: ubuntu
    mode: 754


hooks:
  BeforeInstall:
    - location: scripts/application_before_install.sh
      timeout: 40
      runas: ubuntu
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 40
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 120
      runas: ubuntu